spring.application.name=demo
vsphere.ip=192.168.1.18
vsphere.username=root
vsphere.password=UHP-fsts2023

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=verysecret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Spring Session JDBC Configuration
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

# Security Configuration
encryption.host.key=NgCloud-Secure-Key-2026

# Logging Configuration
logging.file.path=/application/logs

# Configuration optionnelle pour un TrustStore personnalisé (pour la sécurité SSL)
# vsphere.truststore.path=/path/to/your/custom.jks
# vsphere.truststore.password=your_truststore_password

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.vsphere.enabled=true # Active spécifiquement notre HealthIndicator
